
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tomcat-app_42
  labels:
    app: java-tomcat-app_42
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-tomcat-app_42
  template:
    metadata:
      labels:
        app: java-tomcat-app_42
    spec:
      containers:
        - name: java-tomcat-app_42
          image: your-dockerhub-username/java-tomcat-app:latest
          ports:
            - containerPort: 8082
